# -*- coding: utf-8 -*-
"""Ejercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeIoouGpcPQthkZLmlfN0asKaDATylF8
"""

# ==========================================
# PRÁCTICA ACTIVIDAD ASINCRÓNICA
# PROFILADO Y EDA
# ==========================================

# Librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# 1. CREACIÓN DEL DATASET
# ==========================================

data = {
    "cliente_id": [1,2,3,4,5,5,6,7,8,9,10],
    "edad": [25, 30, np.nan, 22, 40, 40, 35, 28, 200, 32, np.nan],
    "ingresos": [50000, 60000, 55000, None, 70000, 70000, 65000, None, 1000000, 62000, 58000],
    "ciudad": ["Buenos Aires", "buenos aires", "CABA", "Cordoba", "Córdoba", "Córdoba", None, "Rosario", "Rosario", "rosario", "Mendoza"]
}

df = pd.DataFrame(data)

print("📌 Dataset inicial")
display(df)

# ==========================================
# 2. PROFILADO DE DATOS
# ==========================================

print("\n📊 Información general")
df.info()

print("\n📊 Estadísticas descriptivas")
display(df.describe())

print("\n❗ Valores nulos por columna")
print(df.isnull().sum())

print("\n🔁 Cantidad de duplicados")
print(df.duplicated().sum())

# ==========================================
# 3. LIMPIEZA DE DATOS
# ==========================================

# Eliminar duplicados
df = df.drop_duplicates()

# Imputación
df["edad"] = df["edad"].fillna(df["edad"].median())
df["ingresos"] = df["ingresos"].fillna(df["ingresos"].mean())

# Normalización de texto
df["ciudad"] = df["ciudad"].str.lower().str.strip()

print("\n🧹 Dataset limpio")
display(df)

# ==========================================
# 4. ANÁLISIS EXPLORATORIO (EDA)
# ==========================================

# Histograma
plt.figure()
plt.hist(df["edad"])
plt.title("Distribución de Edad")
plt.xlabel("Edad")
plt.ylabel("Frecuencia")
plt.show()

# Boxplot
plt.figure()
plt.boxplot(df["ingresos"])
plt.title("Outliers en Ingresos")
plt.show()

# Scatter plot
plt.figure()
plt.scatter(df["edad"], df["ingresos"])
plt.title("Relación Edad vs Ingresos")
plt.xlabel("Edad")
plt.ylabel("Ingresos")
plt.show()

# ==========================================
# 5. DETECCIÓN DE OUTLIERS
# ==========================================

print("\n🚨 Posibles outliers en edad")
display(df[df["edad"] > 100])

print("\n🚨 Posibles outliers en ingresos")
display(df[df["ingresos"] > 200000])

# ==========================================
# 6. REFLEXIÓN (para el alumno)
# ==========================================

print("""
💡 Preguntas para reflexionar:
- ¿Qué problemas de calidad encontraste?
- ¿Cómo impactan en el análisis?
- ¿Qué otras mejoras propondrías?
""")